In [2]:
# Basic analysis of data and shape

import pandas as pd
import numpy as np


base_path = "/Users/shubhamprashar/Desktop/Interview Prep/ml_projects/credit-default-risk/data"
train_path =  base_path + "/application_train.csv"

# pandas -> dataframe is used to read csv
df = pd.read_csv(train_path)

# examples, features(dimensions)
# (307511, 122)
# print(df.shape)
# print(df.head) # prints first few rows
# print(df.columns.tolist()) # prints all the name of dimensions (features) 




# Yes, exactly. df.isna() returns a DataFrame of the same shape with True where a 
# value is null/NaN and False where it's not.
# print(df.isna())

# sums how many null values per column name 
# print(df.isna().sum())

# columns which are categorical and which are numerical
categorical = df.select_dtypes(include='object').shape[1]
numerical = df.select_dtypes(include='number').shape[1]


# unique value per column
# print(df.nunique())

# for every available col this gives the null % 
# print(df.isnull().mean() * 100)


# column name is the index
# Pandas automatically group the data by the index
summary = pd.DataFrame({
    "dtypes" : df.dtypes,
    "categorical" : categorical,
    "numerical" : numerical,
    "missing" : df.isna().sum(),
    "missing_percentage" : df.isna().mean() * 100,
    "unique" : df.nunique()
})

print(summary)

                             dtypes  categorical  numerical  missing  \
SK_ID_CURR                    int64           16        106        0
TARGET                        int64           16        106        0
NAME_CONTRACT_TYPE           object           16        106        0
CODE_GENDER                  object           16        106        0
FLAG_OWN_CAR                 object           16        106        0
...                             ...          ...        ...      ...
AMT_REQ_CREDIT_BUREAU_DAY   float64           16        106    41519
AMT_REQ_CREDIT_BUREAU_WEEK  float64           16        106    41519
AMT_REQ_CREDIT_BUREAU_MON   float64           16        106    41519
AMT_REQ_CREDIT_BUREAU_QRT   float64           16        106    41519
AMT_REQ_CREDIT_BUREAU_YEAR  float64           16        106    41519

                            missing_percentage  unique
SK_ID_CURR                            0.000000  307511
TARGET                                0.000000       2
NAME_CONTRACT_TYPE                    0.000000       2
CODE_GENDER                           0.000000       3
FLAG_OWN_CAR                          0.000000       2
...                                        ...     ...
AMT_REQ_CREDIT_BUREAU_DAY            13.501631       9
AMT_REQ_CREDIT_BUREAU_WEEK           13.501631       9
AMT_REQ_CREDIT_BUREAU_MON            13.501631      24
AMT_REQ_CREDIT_BUREAU_QRT            13.501631      11
AMT_REQ_CREDIT_BUREAU_YEAR           13.501631      25

[122 rows x 6 columns]

In [3]:
summary[ summary["missing_percentage"] >= 40 ].sort_values(ascending=False, by="missing_percentage")

,dtypes,categorical,numerical,missing,missing_percentage,unique
COMMONAREA_AVG,float64,16,106,214865,69.872297,3181
COMMONAREA_MEDI,float64,16,106,214865,69.872297,3202
COMMONAREA_MODE,float64,16,106,214865,69.872297,3128
NONLIVINGAPARTMENTS_MEDI,float64,16,106,213514,69.432963,214
NONLIVINGAPARTMENTS_MODE,float64,16,106,213514,69.432963,167
NONLIVINGAPARTMENTS_AVG,float64,16,106,213514,69.432963,386
FONDKAPREMONT_MODE,object,16,106,210295,68.386172,4
LIVINGAPARTMENTS_MEDI,float64,16,106,210199,68.354953,1097
LIVINGAPARTMENTS_AVG,float64,16,106,210199,68.354953,1868
LIVINGAPARTMENTS_MODE,float64,16,106,210199,68.354953,736
FLOORSMIN_MODE,float64,16,106,208642,67.848630,25
FLOORSMIN_MEDI,float64,16,106,208642,67.848630,47
FLOORSMIN_AVG,float64,16,106,208642,67.848630,305
YEARS_BUILD_MODE,float64,16,106,204488,66.497784,154
YEARS_BUILD_AVG,float64,16,106,204488,66.497784,149
YEARS_BUILD_MEDI,float64,16,106,204488,66.497784,151
OWN_CAR_AGE,float64,16,106,202929,65.990810,62
LANDAREA_MODE,float64,16,106,182590,59.376738,3563
LANDAREA_MEDI,float64,16,106,182590,59.376738,3560
LANDAREA_AVG,float64,16,106,182590,59.376738,3527
BASEMENTAREA_MODE,float64,16,106,179943,58.515956,3841
BASEMENTAREA_MEDI,float64,16,106,179943,58.515956,3772
BASEMENTAREA_AVG,float64,16,106,179943,58.515956,3780
EXT_SOURCE_1,float64,16,106,173378,56.381073,114584
NONLIVINGAREA_MODE,float64,16,106,169682,55.179164,3327
NONLIVINGAREA_AVG,float64,16,106,169682,55.179164,3290
NONLIVINGAREA_MEDI,float64,16,106,169682,55.179164,3323
ELEVATORS_AVG,float64,16,106,163891,53.295980,257
ELEVATORS_MEDI,float64,16,106,163891,53.295980,46
ELEVATORS_MODE,float64,16,106,163891,53.295980,26
WALLSMATERIAL_MODE,object,16,106,156341,50.840783,7
APARTMENTS_MEDI,float64,16,106,156061,50.749729,1148
APARTMENTS_AVG,float64,16,106,156061,50.749729,2339
APARTMENTS_MODE,float64,16,106,156061,50.749729,760
ENTRANCES_AVG,float64,16,106,154828,50.348768,285
ENTRANCES_MEDI,float64,16,106,154828,50.348768,46
ENTRANCES_MODE,float64,16,106,154828,50.348768,30
LIVINGAREA_MEDI,float64,16,106,154350,50.193326,5281
LIVINGAREA_MODE,float64,16,106,154350,50.193326,5301
LIVINGAREA_AVG,float64,16,106,154350,50.193326,5199
HOUSETYPE_MODE,object,16,106,154297,50.176091,3
FLOORSMAX_AVG,float64,16,106,153020,49.760822,403
FLOORSMAX_MEDI,float64,16,106,153020,49.760822,49
FLOORSMAX_MODE,float64,16,106,153020,49.760822,25
YEARS_BEGINEXPLUATATION_AVG,float64,16,106,150007,48.781019,285
YEARS_BEGINEXPLUATATION_MODE,float64,16,106,150007,48.781019,221
YEARS_BEGINEXPLUATATION_MEDI,float64,16,106,150007,48.781019,245
TOTALAREA_MODE,float64,16,106,148431,48.268517,5116
EMERGENCYSTATE_MODE,object,16,106,145755,47.398304,2

In [4]:
summary[ summary["missing_percentage"] >= 60 ].sort_values(ascending=False, by="missing_percentage")

#### All these columns are related to how the person is living (buiding)
#### These information may be optional during collection what is why almost 70% of it is missing
# <------- Description of the data that is having high missing percentage ------->
# COMMONAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 79,application_{train|test}.csv,COMMONAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized


# 65,application_{train|test}.csv,COMMONAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 87,application_{train|test}.csv,NONLIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 73,application_{train|test}.csv,NONLIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 59,application_{train|test}.csv,NONLIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 89,application_{train|test}.csv,FONDKAPREMONT_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 87,application_{train|test}.csv,NONLIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 57,application_{train|test}.csv,LIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

# 71,application_{train|test}.csv,LIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

,dtypes,categorical,numerical,missing,missing_percentage,unique
COMMONAREA_MEDI,float64,16,106,214865,69.872297,3202
COMMONAREA_AVG,float64,16,106,214865,69.872297,3181
COMMONAREA_MODE,float64,16,106,214865,69.872297,3128
NONLIVINGAPARTMENTS_MEDI,float64,16,106,213514,69.432963,214
NONLIVINGAPARTMENTS_AVG,float64,16,106,213514,69.432963,386
NONLIVINGAPARTMENTS_MODE,float64,16,106,213514,69.432963,167
FONDKAPREMONT_MODE,object,16,106,210295,68.386172,4
LIVINGAPARTMENTS_AVG,float64,16,106,210199,68.354953,1868
LIVINGAPARTMENTS_MEDI,float64,16,106,210199,68.354953,1097
LIVINGAPARTMENTS_MODE,float64,16,106,210199,68.354953,736
FLOORSMIN_MEDI,float64,16,106,208642,67.848630,47
FLOORSMIN_MODE,float64,16,106,208642,67.848630,25
FLOORSMIN_AVG,float64,16,106,208642,67.848630,305
YEARS_BUILD_MEDI,float64,16,106,204488,66.497784,151
YEARS_BUILD_AVG,float64,16,106,204488,66.497784,149
YEARS_BUILD_MODE,float64,16,106,204488,66.497784,154
OWN_CAR_AGE,float64,16,106,202929,65.990810,62

## Target Distribution

The dataset contains 307,511 loan applications.

91.9% of applicants belong to class 0 (no payment difficulty).

8.1% of applicants belong to class 1 (payment difficulty).

This indicates a moderately imbalanced classification problem.

In [ ]:
# Raw count
print(df['TARGET'].value_counts())

# gives ratio rather than count
print(df['TARGET'].value_counts(normalize = True))

# We will explore the default based on the gender